spring:
  application:
    name: rag-slack-bot

  ai:
    openai:
      embedding:
        options:
          model: text-embedding-3-small

  servlet:
    multipart:
      max-file-size: 50MB        # Maximum file size
      max-request-size: 50MB     # Maximum request size
      file-size-threshold: 2KB   # Threshold for writing to disk
      location: /tmp             # Temporary location for uploaded files

logging:
  level:
    '[org.springframework.ai]': DEBUG
    '[org.springframework.ai.vectorstore]': DEBUG

chroma-db:
  host: http://localhost
  port: 8000
  initializeSchema: true
  # key-token: <your access token (if configure)>
  # username: <your username (if configure)>
  # password: <your password (if configure)>
  tenant-name: default_tenant
  database-name: default_database
  collections:
    openao:
      prompt-refinements: OPENAI
      initializeSchema: true
    employeehandbook:
      prompt-refinements: keyhole
      initializeSchema: true
